[theme]
#primaryColor="#F63366"
primaryColor="#47C7DA"
backgroundColor="#FFFFFF"
#backgroundColor=="#293745"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
#textColor="white"

font="sans serif"

[Server]
runOnSave = True
enableStaticServing = True